from pymssql import DECIMAL
from sqlalchemy import Column, TEXT
from sqlalchemy.dialects.mssql import MONEY, INTEGER, BIGINT, VARCHAR, BIT
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class CCPGPSCGPHYCLMX(Base):
    __tablename__ = 'ccp_gpsc_gphy_clmx'

    id = Column(BIGINT, primary_key=True)
    scid = Column(BIGINT)
    clid = Column(BIGINT)
    sxs = Column(INTEGER)
    zbid = Column(BIGINT)
    zbdm = Column(VARCHAR)
    zbmc = Column(VARCHAR)
    jyjg = Column(VARCHAR)
    jyjgtz = Column(VARCHAR)
    jyjgbz = Column(VARCHAR)
    jybz1 = Column(VARCHAR)
    jybz2 = Column(VARCHAR)
    jybz3 = Column(VARCHAR)


class XSDYZBZSSCLH(Base):
    __tablename__ = 'xs_dy_zbzs_sclh'

    id = Column(BIGINT, primary_key=True)
    pdid = Column(BIGINT)
    sclh = Column(VARCHAR)
    dyks = Column(INTEGER)
    dyzl = Column(MONEY)


class CLCSHCLXX(Base):

    __tablename__ = 'cl_csh_clxx'
    id = Column(BIGINT, primary_key=True)
    cldm = Column(VARCHAR)
    tdbh = Column(VARCHAR)
    clmc = Column(VARCHAR)
    pym = Column(VARCHAR)
    ggxh = Column(VARCHAR)
    lbid = Column(BIGINT)
    lbmc = Column(VARCHAR)
    flid = Column(BIGINT)
    flmc = Column(VARCHAR)
    ddwid = Column(BIGINT)
    ddwmc = Column(VARCHAR)
    xdwid = Column(BIGINT)
    xdwmc = Column(VARCHAR)
    djid = Column(BIGINT)
    djmc = Column(VARCHAR)
    ckid = Column(BIGINT)
    ckmc = Column(VARCHAR)
    cwid = Column(BIGINT)
    cwmc = Column(VARCHAR)
    rklbid = Column(BIGINT)
    rklbmc = Column(VARCHAR)
    cljj = Column(DECIMAL)
    clpfj = Column(DECIMAL)
    clxsj = Column(DECIMAL)
    kc_qcsl = Column(DECIMAL)
    kc_rks = Column(DECIMAL)
    kc_cks = Column(DECIMAL)
    kc_sl = Column(DECIMAL)
    kc_zmrks = Column(DECIMAL)
    kc_zmcks = Column(DECIMAL)
    kc_zmkcs = Column(DECIMAL)
    kc_aqkcsl = Column(DECIMAL)
    kc_sx = Column(DECIMAL)
    kc_xx = Column(DECIMAL)
    cb_qcs = Column(DECIMAL)
    cb_qcje = Column(DECIMAL)
    cb_ljs = Column(DECIMAL)
    cb_ljje = Column(DECIMAL)
    cb_cbje = Column(DECIMAL)
    sx_gbhp = Column(BIT)
    sx_zjhp = Column(BIT)
    sx_thhhp = Column(BIT)
    sx_dzhp = Column(BIT)
    sx_ccp = Column(BIT)
    sx_ccp_cc_c = Column(MONEY)
    sx_ccp_cc_k = Column(MONEY)
    sx_ccp_cc_g = Column(MONEY)
    sx_ccp_gp = Column(BIT)
    sx_ccp_pt = Column(BIT)
    sx_ccp_pt_300 = Column(BIT)
    sx_ccp_lwg = Column(BIT)
    sx_ccp_lwg_dlw = Column(BIT)
    sx_ccp_lwg_xlw = Column(BIT)
    sx_ccp_lwg_3j = Column(BIT)
    sx_ccp_lwg_4j = Column(BIT)
    sx_ccp_bdc = Column(BIT)
    sx_ccp_bhg = Column(BIT)
    sx_ccp_mrlj = Column(MONEY)
    sx_ccpjyrk = Column(BIT)
    sx_xsfcpzhqr = Column(BIT)
    sx_xsdj = Column(BIT)
    sx_yfhp = Column(BIT)
    sx_azjj = Column(BIT)
    sx_cgcl = Column(BIT)
    sx_rktm = Column(BIT)
    sx_clty = Column(BIT)
    sx_hbcl = Column(BIT)
    sx_cycl = Column(BIT)
    sx_clly = Column(BIT)
    sx_clxs = Column(BIT)
    sx_jshp = Column(BIT)
    sx_tzcl = Column(BIT)
    sx_sxs = Column(INTEGER)
    sx_cggbdksq = Column(BIT)
    sx_bczxh = Column(BIT)
    kz_xxj = Column(BIT)
    sx_bpbj = Column(BIT)
    sx_ccp_bdc_glid = Column(INTEGER)
    sx_ccp_bhg_glid = Column(INTEGER)
    sx_hcpkz = Column(MONEY)
    sx_mrkz = Column(MONEY)
    bz = Column(TEXT)
    sm = Column(TEXT)

